#pragma once

#include "IHasher.hpp"
#include "FibonacciHasher.hpp"

#include <cstdint>
#include <iomanip>
#include <sstream>
#include <span>
#include <string>
#include <type_traits>

// experimental
// generated by ChatGPT
//
// This is a toy byte-stream hasher inspired by Fibonacci multiplication. It is
// useful for experimentation and testing the hasher interface, not for real
// content-addressed blob identity.

namespace hashing {

/**
 * @brief Traits template for FibonacciByteHasher word sizes.
 * @tparam UInt Unsigned integer state type.
 */
template <typename UInt>
struct FibonacciByteHasherTraits;

/** @brief Traits for the 32-bit experimental Fibonacci byte hasher. */
template <>
struct FibonacciByteHasherTraits<std::uint32_t> {
    /** @brief Initial state. */
    static constexpr std::uint32_t seed = 0x811C9DC5u;

    /** @brief Number of hex digits in the output. */
    static constexpr int hexWidth = 8;

    /** @brief Algorithm label stored in metadata. */
    static constexpr const char* algorithm = "fib-byte-32";
};

/** @brief Traits for the 64-bit experimental Fibonacci byte hasher. */
template <>
struct FibonacciByteHasherTraits<std::uint64_t> {
    /** @brief Initial state. */
    static constexpr std::uint64_t seed = 0xCBF29CE484222325ull;

    /** @brief Number of hex digits in the output. */
    static constexpr int hexWidth = 16;

    /** @brief Algorithm label stored in metadata. */
    static constexpr const char* algorithm = "fib-byte-64";
};

/**
 * @brief Experimental streaming byte hasher using Fibonacci multiplication.
 *
 * @tparam UInt `std::uint32_t` or `std::uint64_t` state type.
 */
template <typename UInt>
class FibonacciByteHasher final : public IHasher {
public:
    static_assert(
        std::is_same_v<UInt, std::uint32_t> ||
        std::is_same_v<UInt, std::uint64_t>,
        "FibonacciByteHasher supports only uint32_t and uint64_t"
    );

    /** @brief Construct the hasher in its seed state. */
    FibonacciByteHasher()
        : state_(FibonacciByteHasherTraits<UInt>::seed),
          algorithm_(FibonacciByteHasherTraits<UInt>::algorithm)
    {
    }

    /** @brief Return the algorithm label. */
    const std::string& algorithm() const override {
        return algorithm_;
    }

    /** @brief Feed bytes into the experimental hash state. */
    void update(std::span<const std::uint8_t> data) override {
        for (std::uint8_t byte : data) {
            state_ ^= static_cast<UInt>(byte);
            state_ *= fib::FibonacciTraits<UInt>::constant;
        }
    }

    /** @brief Return the current state as fixed-width uppercase hexadecimal. */
    std::string finalHex() override {
        std::ostringstream out;

        out << std::uppercase
            << std::hex
            << std::setw(FibonacciByteHasherTraits<UInt>::hexWidth)
            << std::setfill('0')
            << state_;

        return out.str();
    }

    /** @brief Reset the hasher to its seed state. */
    void reset() {
        state_ = FibonacciByteHasherTraits<UInt>::seed;
    }

private:
    /** @brief Current hash state. */
    UInt state_;

    /** @brief Cached algorithm label. */
    std::string algorithm_;
};

/** @brief Convenient alias for the 32-bit experimental Fibonacci byte hasher. */
using FibonacciByte32Hasher = FibonacciByteHasher<std::uint32_t>;

/** @brief Convenient alias for the 64-bit experimental Fibonacci byte hasher. */
using FibonacciByte64Hasher = FibonacciByteHasher<std::uint64_t>;

} // namespace hashing
